### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dasl-** [dasl-/lightness#1]
- [ ] add playlists to queue
- [ ] back button
- [ ] favicon
- [ ] add favicon to splash page
- [ ] url bar should scroll away
- [ ] color mode
- [ ] search loading feedback
